version: '3.8'

services:
  website:
    image: website:latest
    container_name: website
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file: ../.env
    restart: always